name: package_info_plus_platform_interface
description: A common platform interface for the package_info_plus plugin.
publish_to: none
version: 3.0.1
homepage: https://github.com/fluttercommunity/plus_plugins
repository: https://github.com/fluttercommunity/plus_plugins/tree/main/packages/

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.15.0
  plugin_platform_interface:
    git: https://github.com/kumsumit/plugin_platform_interface.git

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.4.2
  flutter_lints: ^4.0.0

environment:
  sdk: ">=3.2.0 <4.0.0"
  flutter: ">=3.16.0"
